# Generated by Django 2.1.7 on 2019-03-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'slug')},
        ),
    ]
