# Generated by Django 2.1.7 on 2019-03-09 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
        ('home', '0002_auto_20190306_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.Weblog')),
            ],
        ),
    ]
