# Generated by Django 2.1.7 on 2019-03-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeblogPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog_post',
            name='weblog',
        ),
        migrations.DeleteModel(
            name='blog_post',
        ),
    ]
