# Generated by Django 2.1.7 on 2019-03-03 23:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
